{{- if eq .Values.type "NGINX" }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    weblogic.resourceVersion: domain-v2
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /console
            backend:
              serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              servicePort: {{ .Values.wlsDomain.adminServerPort }}
          - path: /weblogic/ready
            backend:
              serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              servicePort: {{ .Values.wlsDomain.adminServerPort }}
          {{- if or (eq .Values.wlsDomain.domainType "soa") (eq .Values.wlsDomain.domainType "osb") (eq .Values.wlsDomain.domainType "soaosb") }}
          - path: /em
            backend:
              serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              servicePort: {{ .Values.wlsDomain.adminServerPort }}
          - path: /servicebus
            backend:
              serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              servicePort: {{ .Values.wlsDomain.adminServerPort }}
          - path: /sbconsole
            backend:
              serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              servicePort: {{ .Values.wlsDomain.adminServerPort }}
          {{- end }}
          {{- if or (eq .Values.wlsDomain.domainType "soaess") (eq .Values.wlsDomain.domainType "soaessosb") }}
          - path: /em
            backend:
              serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              servicePort: {{ .Values.wlsDomain.adminServerPort }}
          - path: /servicebus
            backend:
              serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              servicePort: {{ .Values.wlsDomain.adminServerPort }}
          - path: /sbconsole
            backend:
              serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
              servicePort: {{ .Values.wlsDomain.adminServerPort }}
          - path: /ess
            backend:
              serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.clusterName | lower | replace "_" "-" }}'
              servicePort: {{ .Values.wlsDomain.managedServerPort }}
          - path: /EssHealthCheck
            backend:
              serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.clusterName | lower | replace "_" "-" }}'
              servicePort: {{ .Values.wlsDomain.managedServerPort }}
          {{- end }}
          - path:
            backend:
              serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.clusterName | lower | replace "_" "-" }}'
              servicePort: {{ .Values.wlsDomain.managedServerPort }}
  {{- end }}
