# Copyright 2018, 2019, Oracle Corporation and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

{{- if eq .Values.type "TRAEFIK" }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-traefik
  namespace: {{ .Release.Namespace }}
  labels:
    weblogic.resourceVersion: domain-v2
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /console
              backend:
                serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
                servicePort: {{ .Values.wlsDomain.adminServerPort }}
          - path: /weblogic/ready
              backend:
                serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
                servicePort: {{ .Values.wlsDomain.adminServerPort }}
          - path:
              backend:
                serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.clusterName | lower | replace "_" "-" }}'
                servicePort: {{ .Values.wlsDomain.managedServerPort }}
          {{- if or (eq .Values.wlsDomain.domainType "soa") (eq .Values.wlsDomain.domainType "osb") (eq .Values.wlsDomain.domainType "soaosb") }}
          - path: /em
              backend:
                serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
                servicePort: {{ .Values.wlsDomain.adminServerPort }}
          - path: /servicebus
              backend:
                serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
                servicePort: {{ .Values.wlsDomain.adminServerPort }}
          - path: /sbconsole
              backend:
                serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
                servicePort: {{ .Values.wlsDomain.adminServerPort }}
          {{- end }}
          {{- if or (eq .Values.wlsDomain.domainType "soaess") (eq .Values.wlsDomain.domainType "soaessosb") }}
          - path: /em
              backend:
                serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
                servicePort: {{ .Values.wlsDomain.adminServerPort }}
          - path: /servicebus
              backend:
                serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
                servicePort: {{ .Values.wlsDomain.adminServerPort }}
          - path: /sbconsole
              backend:
                serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
                servicePort: {{ .Values.wlsDomain.adminServerPort }}
          - path: /ess
              backend:
                serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
                servicePort: {{ .Values.wlsDomain.adminServerPort }}
          - path: /EssHealthCheck
              backend:
                serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
                servicePort: {{ .Values.wlsDomain.adminServerPort }}
          {{- end }}
  {{- end }}
