apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-standalone-firefox
  labels:
    app: selenium-standalone-firefox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-standalone-firefox
  template:
    metadata:
      labels:
        app: selenium-standalone-firefox
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: selenium-standalone-firefox
          image: selenium/standalone-firefox-debug:3.141.59-mercury
          ports:
            - containerPort: 5900
            - containerPort: 4444
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
