apiVersion: v1
kind: Service
metadata:
  name: selenium-standalone-firefox
  labels:
    app: selenium-standalone-firefox
spec:
  ports:
    - port: 5900
      targetPort: 5900
      name: port0
    - port: 4444
      targetPort: 4444
      name: port1
  selector:
    app: selenium-standalone-firefox
