kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: %LB_HELM_RELEASE_NAME%-apache-webtier
  namespace: %DOMAIN_NAMESPACE%
  labels:
    app: %LB_HELM_RELEASE_NAME%-apache-webtier
    weblogic.resourceVersion: "loadbalancer-v2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: %LB_HELM_RELEASE_NAME%-apache-webtier
      weblogic.resourceVersion: "loadbalancer-v2"
  template:
    metadata:
      labels:
        app: %LB_HELM_RELEASE_NAME%-apache-webtier
        weblogic.resourceVersion: "loadbalancer-v2"
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: %LB_HELM_RELEASE_NAME%-apache-webtier-cert
        - name: %LB_HELM_RELEASE_NAME%-apache-webtier
          configMap:
            name: %CUSTOM_CONF_FILE_CONFIGMAP%
            defaultMode: 0777
      containers:
       - env:
         - name: VIRTUAL_HOST_NAME
           value: %APACHE_VIRTUAL_HOST_NAME%
         - name: SSL_CERT_FILE
           value: %CUSTOM_SSL_CERT_FILE%
         - name: SSL_CERT_KEY_FILE
           value: %CUSTOM_SSL_KEY_FILE%
         name: %LB_HELM_RELEASE_NAME%-apache-webtier
         image: %APACHE_WEBTIER_CUSTOM_IMAGE%
         imagePullPolicy: IfNotPresent
         volumeMounts:
           - name: serving-cert
             mountPath: "/var/serving-cert"
           - name: %LB_HELM_RELEASE_NAME%-apache-webtier
             mountPath: "/config/custom_mod_wl_apache.conf"
             subPath: custom_mod_wl_apache.conf
         readinessProbe:
           tcpSocket:
             port: 80
           failureThreshold: 1
           initialDelaySeconds: 10
           periodSeconds: 10
           successThreshold: 1
           timeoutSeconds: 2
         livenessProbe:
           tcpSocket:
             port: 80
           failureThreshold: 3
           initialDelaySeconds: 10
           periodSeconds: 10
           successThreshold: 1
           timeoutSeconds: 2
