apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "slave"
    jenkins/fmwk8s-generic: "true"
spec:
  containers:
    - env:
        - name: "http_proxy"
          value: "http://www-proxy-brmdc.us.oracle.com:80"
        - name: "no_proxy"
          value: ".cluster.local,.us.oracle.com,.oraclecorp.com,100.0.0.0/8,.oraclevcn.com,10.96.0.1,100.111.149.13,100.111.149.15,100.111.149.45"
        - name: "https_proxy"
          value: "http://www-proxy-brmdc.us.oracle.com:80"
      image: "cisystem.docker.oraclecorp.com/fmw-k8s-syseng-oel7-slave:latest"
      imagePullPolicy: "Always"
      name: "jnlp"
      resources:
        limits: {}
        requests:
          memory: "2Gi"
      securityContext:
        privileged: true
      tty: true
      volumeMounts:
        - mountPath: "/fmwk8s"
          name: fmwk8s-pv
        - mountPath: "/scratch/syseng/workspace"
          name: "volume-1"
        - mountPath: "/dev/shm"
          name: "volume-0"
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
      workingDir: "/home/jenkins/agent"
  nodeSelector: {}
  restartPolicy: "Never"
  volumes:
    - name: fmwk8s-pv
      persistentVolumeClaim:
        claimName: fmwk8s-pvc
    - emptyDir:
        medium: "Memory"
      name: "volume-0"
    - emptyDir:
        medium: "Memory"
      name: "volume-1"
    - emptyDir:
        medium: ""
      name: "workspace-volume"
