apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: logstash-%DOMAIN_NAME%
  namespace: %DOMAIN_NAMESPACE%
spec:
  template: # create pods using pod definition in this template
    metadata:
      labels:
        k8s-app: logstash-%DOMAIN_NAME%
    spec:
      volumes:
        - name: domain-storage-volume
          persistentVolumeClaim:
            claimName: %DOMAIN_PVC%
        - name: fmwk8s-logstash-configmap
          configMap:
            name: %DOMAIN_NAME%-logstash-configmap
            defaultMode: 0777
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: logstash
          image: logstash:6.4.3
          command: ["/bin/sh"]
          args: ["/usr/share/logstash/bin/logstash", "-f", "/shared/domains/logstash/logstash.conf"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: domain-storage-volume
              mountPath: /shared/domains
            - name: fmwk8s-logstash-configmap
              mountPath: /shared/domains/logstash/logstash.conf
              subPath: logstash.conf
            - name: shared-logs
              mountPath: /shared-logs
          ports:
            - containerPort: 5044
              name: logstash
