---
apiVersion: v1
kind: Pod
metadata:
  name: fmwk8s-customize-domain
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
    - name: fmwk8s-customize-domain
      image: cisystem.docker.oraclecorp.com/fmw-k8s-syseng-oel7-slave:latest
      imagePullPolicy: Always
      env:
        - name: LB_HOST
          value: "%LB_HOST%"
        - name: LB_PORT
          value: "%LB_PORT%"
      envFrom:
        - configMapRef:
            name: fmwk8s-tests-env-configmap
      command: ["/bin/sh"]
      args: ["-c", "/etc/config/customize-domain.sh"]
      volumeMounts:
        - name: domain-storage-volume
          mountPath: %FMWK8S_NFS_HOME%
        - name: fmwk8s-utility-configmap
          mountPath: /etc/config
        - name: fmwk8s-domain-yaml
          mountPath: /etc/domain
  volumes:
    - name: fmwk8s-utility-configmap
      configMap:
        name: fmwk8s-utility-configmap
        defaultMode: 0777
    - name: domain-storage-volume
      persistentVolumeClaim:
        claimName: %DOMAIN_PVC%
    - name: fmwk8s-domain-yaml
      configMap:
        name: fmwk8s-domain-yaml
        defaultMode: 0777
---
---
