---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fmwk8s-utility-configmap
data:
  run-timer.sh: |-
    #!/bin/bash

    touch ${LOG_DIRECTORY}/fmwk8s.completed

    echo "Retaining Environment for ${HOURS_AFTER_SECONDS} seconds..."
    sleep ${HOURS_AFTER_SECONDS}

  web.xml: |-
    <?xml version = '1.0' encoding = 'US-ASCII'?>
    <web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
             version="2.5" xmlns="http://java.sun.com/xml/ns/javaee">
      <context-param>
        <param-name>javax.faces.PROJECT_STAGE</param-name>
        <param-value>SystemTest</param-value>
      </context-param>
      <context-param>
        <param-name>oracle.adf.view.rich.automation.ENABLED</param-name>
        <param-value>true</param-value>
      </context-param>
    </web-app>

  customize-domain.sh: |-
    #!/bin/sh

    if [ "${PRODUCT_ID}" == "wcp" ]
    then
      echo "copying web.xml to enable rich automation for wcp..."
      cp -Lr /etc/config/web.xml ${FMWK8S_NFS_HOME}/domains/applications/extend.spaces.webapp.war/WEB-INF/
      ls -ltr ${FMWK8S_NFS_HOME}/domains/applications/extend.spaces.webapp.war/WEB-INF
    fi

    if [ "${PRODUCT_ID}" == "wcsites" ]
    then
      echo "invoking sitesconfig setup for wcsites..."
      kubectl get pods -n ${MY_POD_NAMESPACE}
      kubectl apply -f /etc/domain/domain.yaml -n ${MY_POD_NAMESPACE}
      sleep 300
      cat /etc/domain/create-domain-inputs.yaml
      domainUID = `grep -A3 'domainUID:' /etc/domain/create-domain-inputs.yaml | tail -n1 | awk '{ print $2}'`
      clusterName = `grep -A3 'clusterName:' /etc/domain/create-domain-inputs.yaml | tail -n1 | awk '{ print $2}'`
      curl -kv http://$domainUID-cluster-$clusterName.${MY_POD_NAMESPACE}:18001/sites/sitesconfig
      sleep 300
    fi
---
