---
apiVersion: v1
kind: Pod
metadata:
  name: fmwk8s-mkdir
spec:
  securityContext:
    runAsUser: 756208
    fsGroup: 8500
  restartPolicy: Never
  volumes:
    - name: fmwk8s-nfs-home
      hostPath:
        path: %FMWK8S_NFS_HOME%
        type: Directory
  containers:
    - name: fmwk8s-mkdir
      image: k8s.gcr.io/busybox
      command: ["/bin/sh"]
      args: ["-c", "mkdir -p /root/$NFS_DOMAIN_DIR"]
      securityContext:
        runAsUser: 756208
        allowPrivilegeEscalation: true
      env:
        - name: NFS_DOMAIN_DIR
          value: %NFS_DOMAIN_DIR%
      volumeMounts:
        - name: fmwk8s-nfs-home
          mountPath: "/root"
---
---
