---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fmwk8s-utility-configmap
data:
  run-timer.sh: |-
    #!/bin/bash

    touch ${LOG_DIRECTORY}/fmwk8s.completed

    while true; do sleep 86400; done
---
