---
apiVersion: v1
kind: Pod
metadata:
  name: fmwk8s-customize-domain
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
    - name: fmwk8s-customize-domain
      image: cisystem.docker.oraclecorp.com/fmw-k8s-syseng-oel7-slave:latest
      imagePullPolicy: Always
      env:
        - name: PRODUCT_ID
          value: %PRODUCT_ID%
        - name: FMWK8S_NFS_HOME
          value: %FMWK8S_NFS_HOME%
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      command: ["/bin/sh"]
      args: ["-c", "/etc/config/customize-domain.sh"]
      volumeMounts:
        - name: domain-storage-volume
          mountPath: %FMWK8S_NFS_HOME%
        - name: fmwk8s-utility-configmap
          mountPath: /etc/config
        - name: fmwk8s-domain-yaml
          mountPath: /etc/domain
  volumes:
    - name: fmwk8s-utility-configmap
      configMap:
        name: fmwk8s-utility-configmap
        defaultMode: 0777
    - name: domain-storage-volume
      persistentVolumeClaim:
        claimName: %DOMAIN_PVC%
    - name: fmwk8s-domain-yaml
      configMap:
        name: fmwk8s-domain-yaml
        defaultMode: 0777
---
---
