---
apiVersion: v1
kind: Pod
metadata:
  name: fmwk8s-rcu-pod
spec:
  imagePullSecrets:
    - name: %DB_SECRET%
  volumes:
    - name: fmw-rcu-configmap
      configMap:
        name: %PRODUCT_ID%-rcu-configmap
  containers:
    - name: fmwk8s-rcu-pod
      imagePullPolicy: IfNotPresent
      image: %PRODUCT_IMAGE%
      command: ["/bin/sh"]
      args: ["-c", "chmod -R 777 /fmwk8s && /fmwk8s/run-rcu.sh"]
      volumeMounts:
        - mountPath: "/fmwk8s"
          name: fmw-rcu-configmap
---
