---
apiVersion: v1
kind: ConfigMap
metadata:
  name: soa-rcu-configmap
data:
  run-rcu.sh: |-
    #!/bin/bash

    export CONNECTION_STRING=%CONNECTION_STRING%
    export RCUPREFIX=%RCUPREFIX%

    echo -e %SYS_PASSWORD%"\n"%PASSWORD% > /tmp/pwd.txt

    /u01/oracle/oracle_common/bin/rcu -silent -createRepository -databaseType ORACLE -connectString $CONNECTION_STRING -dbUser sys -dbRole sysdba \
    -useSamePasswordForAllSchemaUsers true -selectDependentsForComponents true \
    -variables SOA_PROFILE_TYPE=SMALL,HEALTHCARE_INTEGRATION=NO \
    -schemaPrefix $RCUPREFIX \
    -component MDS \
    -component IAU \
    -component IAU_APPEND \
    -component IAU_VIEWER \
    -component OPSS \
    -component WLS \
    -component STB \
    -component ESS \
    -component SOAINFRA -f < /tmp/pwd.txt
---
