kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.domain.domainUID }}-apache-webtier
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.domain.domainUID }}-apache-webtier
    weblogic.resourceVersion: "loadbalancer-v2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.domain.domainUID }}-apache-webtier
      weblogic.resourceVersion: "loadbalancer-v2"
  template:
    metadata:
      labels:
        app: {{ .Values.domain.domainUID }}-apache-webtier
        weblogic.resourceVersion: "loadbalancer-v2"
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: {{ .Values.domain.domainUID }}-apache-webtier-cert
        - name: {{ .Values.domain.domainUID }}-apache-webtier
        configMap:
          name: {{ .Values.apacheWebtier.customConfigMapFileName }}
          defaultMode: 0777
      containers:
        - env:
            - name: VIRTUAL_HOST_NAME
              value: {{ .Values.apacheWebtier.virtualHostName }}
            - name: SSL_CERT_FILE
              value: {{ .Values.apacheWebtier.sslCertFileMountedPath }}
            - name: SSL_CERT_KEY_FILE
              value: {{ .Values.apacheWebtier.sslKeyFileMountedPath }}
          name: {{ .Values.domain.domainUID }}-apache-webtier
          image: {{ .Values.apacheWebtier.customImage }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: serving-cert
              mountPath: "/var/serving-cert"
            - name: {{ .Values.domain.domainUID }}-apache-webtier
              mountPath: "/config/custom_mod_wl_apache.conf"
              subPath: custom_mod_wl_apache.conf
          readinessProbe:
            tcpSocket:
              port: 80
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 80
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2