apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apacheWebtier.lbHelmRelease }}-apache-webtier-cert
  namespace: {{ .Release.Namespace }}
  labels:
    weblogic.resourceVersion: "loadbalancer-v2"
type: Opaque
data:
  tls.crt: {{ .Values.apacheWebtier.sslCert }}
  tls.key: {{ .Values.apacheWebtier.sslCertKey }}