apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.domain.domainUID }}-apache-webtier
  namespace: {{ .Release.Namespace }}
  labels:
    weblogic.resourceVersion: "loadbalancer-v2"
spec:
  type: NodePort
  selector:
    app: {{ .Values.domain.domainUID }}-apache-webtier
    weblogic.resourceVersion: "loadbalancer-v2"
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: {{ .Values.apacheWebtier.securePortValue }}
      protocol: TCP
      targetPort: {{ .Values.apacheWebtier.securePortValue }}